version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vkonsec
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - connection
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uankit", "-pRifarani"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  djangoapp:
    build: .
    container_name: djangoapp
    working_dir: /app
    command: ["bash", "-c",'python manage.py migrate && python manage.py runserver 0.0.0.0:8000']

    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - connection
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  nginx:
    build:
      context: ./nginx
    networks:
      - connection
    ports:
      - "80:80"
    depends_on:
      - djangoapp
    restart: always
networks:
  connection:
volumes:
  mysql: