apiVersion: v1
kind: Service
metadata:
  name: djangoapp
  namespace: webapps
spec:
  selector:
    app: djangoapp
    version: blue  # Change to "green" when switching
  ports:
    - port: 8000
      targetPort: 8000
