apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangoapp-green
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: djangoapp
      version: green
  template:
    metadata:
      labels:
        app: djangoapp
        version: green
    spec:
      containers:
        - name: djangoapp
          image: bhaktraj/vkonsec:buildid
          workingDir: /app
          command: ["sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          ports:
            - containerPort: 8000
